[package]
name = "nbody_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
target-cpu = "native" # Or a specific architecture
panic = "abort"